# Generated by Django 4.1.7 on 2023-06-11 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="class",
            name="students",
            field=models.ManyToManyField(to="core.student"),
        ),
    ]
